### ISSUE TITLE
"not running or target is remote" on local & running process

### ISSUE THREAD

**Issue by hph86** [longld/peda#107]
When debugging the attached program locally, I receive the warning "not running or target is remote". The debuggee is still running. I am using latest master branch of peda (836b7b6d3433078eb377596e02f5d9985aa4d160). The symptoms are identical to #20.

I could trace the problem back to `execute_redirect("info program")` in `get_status()` returning `The program being debugged is not being run.`. So I am not sure if this is really a peda problem. However, without loading peda, plain gdb is not fooled into believing the process has terminated.

[peda-bug.txt](https://github.com/longld/peda/files/1137089/peda-bug.txt)

**Comment by longld** [comment]
It's not a bug, peda sets `follow-fork-mode` to `child` when default gdb sets it to `parent`. You can change it to match your needs.

**Comment by hph86** [comment]
Ahw, sorry! Thank you very much and my apologies for the inconvenience.
