### ISSUE TITLE
peda can't run properly on python2.6 ?

### ISSUE THREAD

**Issue by cpeggg** [longld/peda#109]
Does python2.6+ means that peda can't support on elder version of python?
test on centOS6.9 (Linux 2.6) which has installed python2.6 initially and gdb has dynamically linked to it, however peda didn't work.
After reinstalled python 2.7 using yum, remove old gdb and downloaded source code of gdb 7.6 and makefile, peda could work again.
*Just post this issue for some out-dated Linux user such as students taking operating system lessons.*

**Comment by Droid-MAX** [comment]
peda depends Python 3+ ?

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tmfink** [comment]
Python 2.7 also works. PEDA is co-compatible with Python 2/3.
