### ISSUE TITLE
GDB-peda in alpine container

### ISSUE THREAD

**Issue by fpasquer** [longld/peda#114]
Hello, I'm doing a docker container to développe C project.

This all must down, I have just a problem with gdb-peda.

This is the part in my Dockerfile about gdb-peda. (of course gdb (7.12.1) works well):
`# install gdb-peda
RUN apk add --no-cache busybox ;\
wget http://github.com/longld/peda/archive/master.zip ;\
busybox unzip master.zip ;\
echo 'alias gdb-peda="gdb -x /peda-master/peda.py"' >> /root/.zshrc ;\
rm -rf master.zip`

When i run gdb-peda in the container, this is the error:

> ~ # gdb-peda -q
/peda-master/peda.py:8: Error in sourced command file:
Undefined command: "from".  Try "help".
(gdb)

Have you got an idea where it's from?

I followed the official [tutorial](https://github.com/longld/peda) to install gbd-peda, it's same. I get an error in .gdbinit
  
ps: In the container, python 2.7.14 is installed

**Comment by longld** [comment]
gdb in alpine is not compiled with python support. You can type `python` at gdb prompt to check.
