### ISSUE TITLE
add on/off options for printing context

### ISSUE THREAD

**Issue by cheesechoi** [longld/peda#119]
Hi.
I use gdb with script, specially when I encounter reversing problem, it could be better if I can use switch for printing default context. but I couldn't found about this options or code in repo. is there options already ?

**Comment by longld** [comment]
If you use gdb with script, you can switch context on/off by calling to `peda.save_user_command("hook-stop")` and `peda.restore_user_command("hook-stop")`.

**Comment by cheesechoi** [comment]
Thanks! script works well. I wrote like this.

```
python
peda.save_user_command("hook-stop")
end

break *0x0000000000400535
  commands
    silent
    printf "maybe you can found this strings, %s\n", *(char**)$rsi
  end

r abcd
c

python
peda.restore_user_command("hook-stop")
end
```
