### ISSUE TITLE
bug - layout asm

### ISSUE THREAD

**Issue by saturn99** [longld/peda#124]
ind `GDB` go to `layout asm` mode  ,, color not processed

![screenshot from 2018-06-17 02-13-11](https://user-images.githubusercontent.com/5188799/41502654-64d1f0ee-71d4-11e8-87a0-d7f64da126af.png)

**Comment by tonybounty** [comment]
Same problem.
Ubuntu 18.10, gnome terminal 3.30.1

![peda](https://user-images.githubusercontent.com/47276302/55277453-c1521c00-5300-11e9-8037-aca884d46641.png)
