### ISSUE TITLE
Older gdb opening instead of gdb-peda

### ISSUE THREAD

**Issue by TarushS** [longld/peda#140]
![Annotation 2019-08-12 205356](https://user-images.githubusercontent.com/38459708/62876809-62d38a80-bd43-11e9-8e8f-b3389d147101.png)

I tried everything to run gdb-peda but normal gdb runs

**Comment by TarushS** [comment]
/root/.gdbinit:1: Error in sourced command file:
Undefined command: "".  Try "help".

**Comment by adi928** [comment]
Can you do "less ~/.gdbinit"?

There is a blank line which might be the culprit.

**Comment by Manikantsingh** [comment]
Did you guys get the solution for it?
I am also facing the same issue when I use source code to make and install it on my local environment.
peda gdb works fine when it's installed with apt package manager.

**Comment by TarushS** [comment]
@Manikantsingh check your ~/.gdbinit and make sure there is no other line except 
``source ~/peda/peda.py``
