### ISSUE TITLE
color is not working, when gdb with option "-tui"

### ISSUE THREAD

**Issue by lieanu** [longld/peda#23]
Hi,
When i use gdb with option "-tui" or cgdb, the color of peda is not working.
Just like this:
^A^[[;31m^Bgdb-peda$ ^A^[[0m^B  (gdb with -tui)
[;31mgdb-peda$ [0m  (cgdb)

Is there any solution to deal with this case?

**Comment by cirosantilli** [comment]
+!

**Comment by jxu** [comment]
The problem is tui mode uses curses and it's not easy to simple ANSI colors. https://stackoverflow.com/questions/4373690/ansi-colors-in-c-and-ncurses
