### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by shibumi** [longld/peda#43]
hello,
could you please work with release-tag-function in github? this would help me to make my maintainer job. IIf you would do that I could offer a peda-git package and a peda-stable package. thx!

greetings

Chris

**Comment by shibumi** [comment]
is this project dead? in case of yes.. could I adopt it please?

**Comment by danghvu** [comment]
lol almost, ... recent patches makes me unsure whether it is stable to make a release. Are you comfortable with the current commit in master ?

**Comment by shibumi** [comment]
I am comfortable with teh current commit in master. But I am not using all features.. I will ask some of my Friends. They are using PEDA a lot more..

**Comment by tmfink** [comment]
I think master is pretty stable because I test almost all of the commands in PEDA with https://github.com/tmfink/peda-test. However, the tests do not cover each variant of each command. Also, the tests are not fully automatic; they require human eyes.

**Comment by anthraxx** [comment]
I'm using peda on a regular basis (with both, gdb with python2 and gdb with python3) and working with a lot of peda commands... did not yet spot any problems :+1:

**Comment by danghvu** [comment]
@tmfink Test are great! I have an "ongoing work" for automated unit tests here, could you have a look and see if you can merge your change into ?

https://github.com/danghvu/peda/blob/master/peda_test.py

**Comment by tmfink** [comment]
@danghvu I like how your tests are actually automated and can test each unit; I'll try to add some more.

However, I think we should also do integration-style testing where we look at the PEDA output. I also like how, with my scripts, you can compare different versions of PEDA/GDB, which is useful for checking Python 2/3 compatibility.

**Comment by danghvu** [comment]
If you point me to the file that you do integration testing, I will try to make an automated one for it. I'd love to merge all test and push to the mainstream. That way we have more confident on a actual release.

**Comment by tmfink** [comment]
Run a diff on test between two different PEDA/GDB versions:
https://github.com/tmfink/peda-test/blob/master/compare_pedas.sh

Run a test on a given version of PEDA/GDB:
https://github.com/tmfink/peda-test/blob/master/run_peda_test.sh

**Comment by anthraxx** [comment]
nearly one year passed... how about tagging a release
PS: don't fear it... release fast and release often  :smile_cat:

**Comment by longld** [comment]
OK, just made it to v1.1

**Comment by anthraxx** [comment]
yay finally :tada: :balloon: guess we can close the ticket now :smile:

**Comment by shibumi** [comment]
@longld Thank you a lot!
