### ISSUE TITLE
x/c don't shows the char-equivalent

### ISSUE THREAD

**Issue by shibumi** [longld/peda#44]
Hello,
I have a string in the EAX-Register:
```
gdb-peda$ x/x $eax
0xbffff230:	0x34333231
gdb-peda$ x/s $eax
0xbffff230:	"12345"
```

When I only want the first char gdb can do this:

```
gdb$ x/c $eax
0xbffff230: 31 '1'
```

But PEDA does this:

```
gdb-peda$ x/c $eax
0xbffff230:	0x31
```

Is there a way to fix this issue?

**Comment by longld** [comment]
As default output-radix is set to 16, you can set back to 10: 
gdb-peda$ set output-radix 10
