### ISSUE TITLE
[peda.py] GDB output-radix seems invalid

### ISSUE THREAD

**Issue by R1kk3r** [longld/peda#53]
The documentation says that the value of "output-radix" must be a decimal value of either 8,10 or 16. In peda.py, the value is 0x10... Even if 0x10 set the output-radix to 16, it should be written 16 in peda.py.

Another problem: If output-radix is set to 16 instead of 10, the command "x /1cb <addr>" will not show the character anymore...Don't know if it's a bug or a desired effect but unless this configuration (output-radix 16) is really important for peda, I would suggest to switch back output-radix to default value (10).

**Comment by longld** [comment]
It's not a bug when setting output-radix to 0x10 (16). All peda outputs are in hex, so it is better to keep that.

peda's "hexdump" can be used as alternative to "x /1cb".
