### ISSUE TITLE
Add option for maximum pointer follow depth

### ISSUE THREAD

**Issue by gsingh93** [longld/peda#62]
When displaying a value with `context stack` or `context reg`, if the value is a long chain of pointers, all of these pointers get printed regardless of the length of the chain. Thus, printing one of these values can take a long time (for example, after a large number of recursive calls ebp is a long chain of pointers). There should be an option to stop following these pointers after a certain depth.

**Comment by longld** [comment]
Added fix depth=5 limit in b7c7d7a.

**Comment by anthraxx** [comment]
gues this can also be closed then
