### ISSUE TITLE
Crash upon running a `searchmem` on a core dump

### ISSUE THREAD

**Issue by jaybosamiya** [longld/peda#65]
Here's a minimal working example:

The following file is compiled using `gcc -fno-stack-protector -o a.out`:
```C
#include <string.h>

int main(int argc, char **argv) {
    char buf[8];
    strcpy(buf, argv[1]);
    return 0;
}
```
This is run using
```shell
ulimit -c unlimited
./a.out 123456789012345678901234567890
```
Launching peda with `gdb a.out core` and then running a `searchmem '12345678'` causes it to abort and dump core.

**Comment by longld** [comment]
Most of PEDA commands will not work properly without attaching to a running process, some caused by gdb bug.
