### ISSUE TITLE
rop_search silently failing

### ISSUE THREAD

**Issue by noleti** [longld/peda#67]
Just a usability suggestion: ropsearch is currently failing pretty quietly. I have two suggestions:
- If no asm was generated, just let the user know. Currently, it looks like no gadget was found, which is something different imho
- If 'nasm' is not installed, all asm compilations fail (of course), but there is no error message. The instructions also don't explicitly mention nasm as pre-requisite. Would it make sense to either raise an error/warning, or list this as pre-requisite?

**Comment by longld** [comment]
Added some checks in a7a9a7e. Thanks.
