### ISSUE TITLE
normal behaviour of return

### ISSUE THREAD

**Issue by the-st0rm** [longld/peda#72]
I started to use gdb-peda but there is a default configuration which is very annoying to me and I can't live without it. I am sure it can be reconfigured easily but I have googled and tried to look in different places but I couldn't find anything about it

Basically, when you do something like `x/wx $esp` gdb-peda will print one word starting from the address stored in $esp... when I press **enter** the default behaviour of gdb it will do the following `x/wx $esp+0x4` and it keep viewing more data every time I press enter. I can't get the same behaviour in gdb-peda .. when I press **enter** it repeats the last command which is `x/wx $esp `

any ideas?

**Comment by longld** [comment]
Tested on Ubuntu 12.04 with gdb+python2.x and confirmed that behavior. On Ubuntu 14.04 with gdb+python3.x it just works as usual.

Workaround: retype your command without parameter then you can press **enter** to repeat.
