### ISSUE TITLE
Something wrong with debugging peda.py in Linux?

### ISSUE THREAD

**Issue by binzhikuwen** [longld/peda#74]
I want to ask something about how to debug with peda.py.
I ran into following
`python peda.py
`
`
Traceback (most recent call last):
  File "peda.py", line 5968, in <module>
    class pedaGDBCommand(gdb.Command):
NameError: name 'gdb' is not defined
`
but if I type gdb,everything works fine.

**Comment by longld** [comment]
Runing `peda.py` directly is not the correct way, it must be used inside `gdb`.

**Comment by binzhikuwen** [comment]
I know that run peda.py directly is not the right way.But if you encounter a bug when running this script.How to debug this program,just printing log?

**Comment by FlyRabbit** [comment]
Hello,I met this problem too,did you solve it?

**Comment by crushcc** [comment]
when I use gdb,I have some troubles,like"build/bdist.linux-x86_64/wheel/peda/peda.py: no such file or directory".Anyone know how to deal this?

**Comment by Nikhil1R** [comment]
i got same error so figured it out and here its solution
if you are using debian versions like ubuntu or kali linux 
install (gdb) first by using following command on terminal
root@kali:~# sudo apt-get update 
root@kali:~# sudo apt-get install gdb
now check if gdb is running correctly in your linux by entering command
root@kali:~#gdb
....
....
...
gdb$quit

root@kali:~#git clone https://github.com/longld/peda.git ~/peda
Cloning into '/root/peda'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 351 (delta 0), reused 4 (delta 0), pack-reused 347
Receiving objects: 100% (351/351), 320.67 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (218/218), done.
root@kali:~# echo "source ~/peda/peda.py" >> ~/.gdbinit
root@kali:~# echo "DONE! debug your program with gdb and enjoy"
DONE! debug your program with gdb and enjoy

now if you enter gdb in your terminal window then you will see that gdb peda will be opened instead for gdb

root@kali:~# gdb
GNU gdb (Debian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".

warning: ~/root/Downloads/repos/peda/peda.py: No such file or directory
gdb-peda$ quit

**Comment by Nikhil1R** [comment]
and before installing gdb and peda first remove gdb 
root@kali:~#sudo apt-get remove gdb
root@kali:~# sudo apt-get remove --auto-remove gdb

**Comment by cooook** [comment]
warning: ~/peda/peda.py: No such file or directory
I want to know if I need to download peda.py

**Comment by 0xh0n3y** [comment]
Yes,firstly completely remove gdb and peda and then after , install peda after installing gdb. And you don't need to download peda.py separately because if you install using command then it will automatically download peda.py .
