### ISSUE TITLE
GDB Peda on Mac environment

### ISSUE THREAD

**Issue by minhtt159** [longld/peda#75]
I want to ask if GDB Peda is Mac supported?
[http://s31.postimg.org/fbfsp592z/Screen_Shot_2016_04_22_at_10_35_12_AM.png](url)
Something is wrong here.

**Comment by longld** [comment]
So far only Linux is supported.

**Comment by longld** [comment]
Please check 2dae43f, `peda` can work on OSX with some basic functions

**Comment by minhtt159** [comment]
It's really helpful. Thanks
