### ISSUE TITLE
Ubuntu14.04

### ISSUE THREAD

**Issue by pinkomeo** [longld/peda#77]
GNU gdb (Ubuntu/Linaro 7.4-2012.02-0ubuntu2) 7.4-2012.02
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
/home/pinko/.gdbinit:1: Error in sourced command file:
**Undefined command: "peda".  Try "help".**
Reading symbols from /home/pinko/Desktop/guestbook...(no debugging symbols found)...done.

python version is 2.7 
i don't know why : -(

thx

**Comment by longld** [comment]
Looks strange, please check installation instruction at: https://github.com/longld/peda and post content of your `.gdbinit`

**Comment by pinkomeo** [comment]
**thank you!**
the content of my `.gdbinit` was wrong !

**Comment by xiaoxiyouran** [comment]
I am also get the same mistake.
user00|09:52:50@~$ echo "source ~/peda/peda.py" >> ~/.gdbinit
user00|09:52:59@~$ gdb 
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-50.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
gdb-peda$ start 
'Undefined command: s\x00\x00\x00t\x00\x00\x00a\x00\x00\x00r\x00\x00\x00t\x00\x00\x00. Try "peda help"'

**Comment by xiaoxiyouran** [comment]
gdb 
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-50.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
gdb-peda$ start 
'Undefined command: s\x00\x00\x00t\x00\x00\x00a\x00\x00\x00r\x00\x00\x00t\x00\x00\x00. Try "peda help"'

**Comment by frustreated** [comment]
the same issue occured on my computer
