### ISSUE TITLE
`checksec` on OSX appears to be buggy

### ISSUE THREAD

**Issue by OJ** [longld/peda#94]
Hi,

First, thanks for the effort in making peda, it's wonderful.

While playing with it on OSX recently I found that it wasn't correctly identifying flags for the binary with regards to the `checksec` feature. For example:

```
$ gcc -o derp derp.c -m32 -Wl,-allow_stack_execute
$ otool -hv derp
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
   MH_MAGIC    I386        ALL  0x00     EXECUTE    15       1044   NOUNDEFS DYLDLINK TWOLEVEL ALLOW_STACK_EXECUTION PIE MH_NO_HEAP_EXECUTION
$ gdb ./derp
.
.
gdb-peda$ checksec
CANARY    : disabled
FORTIFY   : disabled
NX        : ENABLED
PIE       : disabled
RELRO     : disabled
```
I haven't tested `RELRO` but from what I can tell, all of the other flags in this list appear to be incorrect, regardless of the compilation flags.

Thanks.

**Comment by longld** [comment]
Hi,

`checksec` is based on `checksec.sh` which is Linux specific. You can write a wrapper for `otool` if you want that feature on OSX.
