### ISSUE TITLE
BuG

### ISSUE THREAD

**Issue by axeryder19** [longld/peda#96]
hello there,
i have found a bug in the peda i'd like to report for fixing.
with the intel x86 instruction inconditional jump **JMP** if you jump to a register ex: **jmp eax** the peda show that the jmp is not taken but instead it is taken in gdb. i was doing some debbuging fo biniray obfiscation and that bug just give me a hard day intil i noticed that some jumps are taken but peda shows that they are not ... thanks for this really nice software and please fix the bugs as soon as possible.

![screenshot_20170123_114318](https://cloud.githubusercontent.com/assets/16355860/22203159/997ead6c-e163-11e6-9ca9-3d1519f59f62.png)
![screenshot_20170123_114337](https://cloud.githubusercontent.com/assets/16355860/22203193/b57dfc3e-e163-11e6-98b6-d39cbc618638.png)

best regards.
Anass BOUCHNAFA

**Comment by longld** [comment]
Fixed in https://github.com/longld/peda/commit/5458dd5ba8e2b86c20aed223678d916062dc335d, please check.

Thanks.

**Comment by axeryder19** [comment]
thanx again, the bug is fixed.
